stages:
  - test

.test_template: &test_definition
  stage: test
  # don't start any services (mailny not the default ones)
  services:
  script:
    - dnf -y install python2 python2-devel rpm-python python-tox python-pip python-setuptools gcc redhat-rpm-config git openscap openscap-engine-sce openscap-utils pykickstart python-requests
    #- pip install tox setuptools
    - tox --recreate

test:f23:
  <<: *test_definition
  image: fedora:23

test:f24:
  <<: *test_definition
  image: fedora:24

test:rawhide:
  <<: *test_definition
  image: fedora:rawhide

