# Include warnings about missing documentation?
doc-warnings: True

# Include warnings about tests?
test-warnings: False

# tests stricktness
strictness: medium
max-line-length: 120

# autodetect dependencies?
autodetect: True

# paths to be ignored
ignore-paths:
    - docs
    - preup_ui
    - setup.py
    - tests
    - preup/script_api.py
